
CREATE DATABASE qrcodedb
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE qrcodedb;

CREATE TABLE events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    event_date DATE NOT NULL UNIQUE
);

CREATE TABLE table_attendance (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENTID VARCHAR(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    STUDENTNAME VARCHAR(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    YEAR_SECTION VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    TIMEIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIMEOUT TIMESTAMP NULL DEFAULT NULL,
    LOGDATE DATE DEFAULT CURRENT_DATE,
    STATUS TINYINT(1) DEFAULT 0,
    EVENT VARCHAR(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    ATTENDANCE VARCHAR(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'On Time',
    event_id INT,
    FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE,
    password VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
);

CREATE TABLE addqr (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id VARCHAR(255) NOT NULL,
    student_name VARCHAR(255) NOT NULL,
    year_section VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO users (username, password) VALUES ('ITSsociety', PASSWORD('informationtechnology'));
